---
# tasks file for ansible-repo
- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash
    generate_ssh_key: yes
- name: Enable ssh auth for deploy
  authorized_key:
    user: deploy
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items: "{{ ssh_key_paths }}"
- name: ensure bibucket.org is a known host
  known_hosts:
    name: bitbucket.org
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa bitbucket.org') }}"
  become: yes
  become_user: deploy